Repository Lucidiot/PseudoScience, pull requests merged in 2018-02, with the labels that each got.

#63 Ajout de plusieurs unités du système impérial
  pseudosci/units/general.py
Labels: enhancement

#64 Ajout de l'unité **SufaceTension**
  pseudosci/units/general.py
Labels: enhancement

#65 Ajout d'un cache pip
  .travis.yml
Labels: enhancement, low priority

#66 Ajout de documentations
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: low priority

#70 Fix des puissances
  .vscode/tasks.json
  pseudosci/relativity.py
  pseudosci/units/__init__.py
  pseudosci/units/general.py
  pseudosci/units/tests/test_unit.py
Labels: bug
